backend:
  name: git-gateway
  branch: master
media_folder: public/uploads
public_folder: uploads
slug:
  encoding: "ascii"
  clean_accents: true
collections:
  - name: "pages"
    label: "Strony"
    files:
    - label: "Kontakt"
      name: "contact"
      file: "content/contact.md"
      fields:
        - { label: "Adres Linia 1", name: "address1", widget: "string"}
        - { label: "Adres Linia 2", name: "address2", widget: "string"}
        - { label: "Telefon 1", name: "phone1", widget: "string"}
        - { label: "Telefon 2", name: "phone2", widget: "string"}
        - { label: "E-mail 1", name: "email", widget: "string"}
        - { label: "E-mail 2", name: "email2", widget: "string"}
        - { label: "Fax 1", name: "fax1", widget: "string"}
        - { label: "Fax 2", name: "fax2", widget: "string"}
        - { label: "Nagłówek formularza", name: "head", widget: "string"}
        - { label: "Nagłówek formularza 2", name: "subhead", widget: "string"}
        
  - name: "components"
    label: "Komponenty strony"
    files:
    - label: "Home slider"
      name: "componentSlider"
      file: "content/componentSlider.md"
      fields:
        - label: 'Slider zawartość'
          name: "homeMainSlider"
          widget: list
          fields:
            - { label: "Tytuł", name: "title", widget: "string"}
            - { label: "Podtytuł", name: "subtitle", widget: "text"}
            - { label: "Zawartość", name: "content", widget: "text"}
            - { label: "Grafika", name: "imgUrl", widget: "image"}
    - label: "O mnie"
      name: "componentAboutUs"
      file: "content/componentAboutUs.md"
      fields:
        - { label: "Tytuł", name: "title", widget: "string"}
        - { label: "Zawartość", name: "content", widget: "markdown"}
        - { label: "Grafika", name: "imgUrl", widget: "image"}
    - label: "Współpraca z firmami"
      name: "componentBrands"
      file: "content/componentBrands.md"
      fields:
        - label: 'Dodaj logo'
          name: "Brands"
          widget: list
          fields:
            - { label: "Tytuł", name: "title", widget: "string"}
            - { label: "Grafika", name: "imgUrl", widget: "image"}
    - label: "Wyróżnione wpisy"
      name: "componentPopularBlog"
      file: "content/componentPopularBlog.md"
      fields:
        - { label: "Zawartość", name: "content", widget: "markdown"}

  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Tutuł", name: "title", widget: "string"}
      - {label: "Data publikacji", name: "date", widget: "datetime"}
      - {label: "Zawartość", name: "content", widget: "markdown"}
      - {label: "Wyróżniony wpis?", name: "isPopular", widget: "boolean", default: false}
      - {label: "Tagi", name: "tags", widget: "string"}
      - label: "Zdjęcia"
        name: "galleryImages"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}
      - label: "Wideo"
        name: "blogVideoLink"
        widget: "file"
        required: false